qml/EpisodeItem.qml, qml/PlayerPage.qml
For users to know easily whether the episode is video or audio.
=> Video indicator sailfish

qml/AllEpisodesPage.qml
Refactored naming to make it filter agnostic.
Addresses gpodder/gpodder-sailfish#52
=> Default filter set to 'Downloaded'. 

gpodder-sailfish.pro, qml/ImportOPML.qml, qml/PodcastsPage.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish.ts
Adds UI interface to OPML import/export functions, still needs https://github.com/gpodder/gpodder-ui-qml/pull/9 to merge and the subunit to be updated.
=> OPML Import/Export support

qml/PodcastDetail.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish.ts
This adds the ability to edit the "section" of a podcast thus allowing to organize your podcasts a bit.
Go to the podcast details page and long click the section field to do this.
Your feedback before merging would be greatly appreciated @carmenfdezb  @sfbg
=> Edit section

qml/PlayerCover.qml, qml/PlayerPage.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish.ts
Let's keep this one open until we agree that the design issues are aligned ans solved completely.
=> App cover and player page improvements, part 2

gpodder-sailfish.pro, rpm/harbour-org.gpodder.sailfish.spec
[translation] Updated German translation by mibuthu
[translation] Fixed Chinese (zh) translation by dashinfantry
[version] bumped to 4.8.1
=> [translation] Added Swedish translation by eson57

gpodder-sailfish.pro, qml/EpisodeItem.qml, qml/PodcastDetail.qml, rpm/harbour-org.gpodder.sailfish.spec, translations/harbour-org.gpodder.sailfish-bg.ts
This adds duration information to 2 possible locations in the Episode list:
* episode menu
* subtitle
Personally I think the subtitle option is better but I figured I would present both and get your opinions before remove one or the other...
Please note you need to add total_time in main.py of gpodder-ui-qml (https://github.com/gpodder/gpodder-ui-qml/pull/11)
Please also note I'm leaving both PRs (gpodder-core and gpodder-ui-qml) open for now and will roll 4.9 version number bumps into them before merging.
@carmenfdezb @sfbg
=> Duration menu

qml/AboutPage.qml, qml/EpisodeItem.qml, qml/PodcastsPage.qml, rpm/harbour-org.gpodder.sailfish.spec
Small UI fixes and update core and ui-qml to 4.10.0
=> Ui bugfixes

qml/EpisodeItem.qml
localization missing, because no locale is set in python
=> added published date to episode item

.gitmodules, common/GPodderAutoFire.qml, common/GPodderCore.qml, common/GPodderDirectorySearchModel.qml, common/GPodderEpisodeListModel.qml, common/GPodderEpisodeListModelConnections.qml, common/GPodderPlatform.qml, common/GPodderPlayback.qml, common/GPodderPodcastListModel.qml, common/GPodderPodcastListModelConnections.qml, common/README.md, common/constants.js, common/main.py, common/util.js, gpodder-sailfish.pro, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish-pl.ts, translations/harbour-org.gpodder.sailfish-ru.ts, translations/harbour-org.gpodder.sailfish-sv.ts, translations/harbour-org.gpodder.sailfish-zh_CN.ts, translations/harbour-org.gpodder.sailfish.ts
Removes gpodder-ui-qml dependency
@thigg @sfbg @carmenfdezb as far as I can tell I did not break anything but I would like to hear other OKs before I merge.
@thigg once this is merged it would be great if you can rebase your PRs on this.
=> Remove ui qml

common/GPodderEpisodeListModel.qml, common/GPodderEpisodeListModelConnections.qml, common/GPodderPlayback.qml, common/GPodderPodcastListModelConnections.qml, common/main.py, common/util.js, qml/EpisodeItem.qml, qml/EpisodesPage.qml, qml/Main.qml, qml/MprisPlayer.qml, qml/PlayerPage.qml
I'm not too sure about the benefit this provides over the risk that it might break something.
I still thought I should do it ;)
This isn't based on the most up-to-date master, as I cant deploy it in my emulator.
=> simple codecleanups, mostly removed warning from using == instead of ===

common/GPodderPlayback.qml, common/main.py, qml/PlayerPage.qml, rpm/harbour-org.gpodder.sailfish.spec, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish-pl.ts, translations/harbour-org.gpodder.sailfish-ru.ts, translations/harbour-org.gpodder.sailfish-sv.ts, translations/harbour-org.gpodder.sailfish-zh_CN.ts, translations/harbour-org.gpodder.sailfish.ts
Adds playback rate control.
There are 2 minor UI issues:
1. I would like the "Playback speed: X" to be centered better, I suspect I can resolve that with implicit width and maybe an additional containing Item.
2. The slider is not displayed in full in the dropdown menu, I'm not sure how big a deal this is
Speed range is 0.5-3.0 in 0.05 steps, 3x seems to be the upper limit of pitch correction while maintaining understandable audio as far as I can tell.
=> Speed adjust

common/GPodderPlayback.qml, common/main.py, qml/ArtArea.qml, qml/PlayerPage.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish-pl.ts, translations/harbour-org.gpodder.sailfish-ru.ts, translations/harbour-org.gpodder.sailfish-sv.ts, translations/harbour-org.gpodder.sailfish-zh_CN.ts, translations/harbour-org.gpodder.sailfish.ts
This is an initial version of a video player there is plenty of room for improvement, for instance I have as yet not figured out how to switch between fullscreen and tiny mode.
It works nice enough though.
=> Video player

common/main.py
=> Opml import

common/GPodderCore.qml, common/GPodderEpisodeListModel.qml, common/GPodderEpisodeListModelConnections.qml, common/GPodderPodcastListModel.qml, qml/AllEpisodesPage.qml, qml/EpisodeFilterDialog.qml, qml/EpisodesPage.qml, qml/Main.qml, qml/PodcastsPage.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish-pl.ts, translations/harbour-org.gpodder.sailfish-ru.ts, translations/harbour-org.gpodder.sailfish-sv.ts, translations/harbour-org.gpodder.sailfish-zh_CN.ts, translations/harbour-org.gpodder.sailfish.ts
Reverts gpodder/gpodder-sailfish#151
=> Revert "AllEpisodes Page updates"

qml/PlayerPage.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish-pl.ts, translations/harbour-org.gpodder.sailfish-ru.ts, translations/harbour-org.gpodder.sailfish-sv.ts, translations/harbour-org.gpodder.sailfish-zh_CN.ts, translations/harbour-org.gpodder.sailfish.ts
1. Speed slider increments of 0.25 instead of 0.05
2. Change player page in both portrait and landscape hopefully for the better
=> UI improvements

common/main.py, qml/SettingsPage.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish-pl.ts, translations/harbour-org.gpodder.sailfish-ru.ts, translations/harbour-org.gpodder.sailfish-sv.ts, translations/harbour-org.gpodder.sailfish-zh_CN.ts, translations/harbour-org.gpodder.sailfish.ts
Reorganization of the Settings page, hopefully improving usability.
This also includes the other PR because I was lazy and did not merge it before doing this one, we'll still merge them separately.
=> Rearrange settings

common/GPodderCore.qml, common/main.py, qml/GpodderNotifications.qml, qml/Main.qml
Add error feedback through QML/SFOS Notifications.
=> Notifications

common/main.py, rpm/harbour-org.gpodder.sailfish.spec
Version bump of gpodder-sailfish and gpodder-core
=> Version 4.17.0

common/main.py, rpm/harbour-org.gpodder.sailfish.spec
=> Fix downloads

common/main.py, qml/Main.qml, translations/harbour-org.gpodder.sailfish-bg.ts, translations/harbour-org.gpodder.sailfish-de.ts, translations/harbour-org.gpodder.sailfish-es.ts, translations/harbour-org.gpodder.sailfish-it.ts, translations/harbour-org.gpodder.sailfish-pl.ts, translations/harbour-org.gpodder.sailfish-ru.ts, translations/harbour-org.gpodder.sailfish-sv.ts, translations/harbour-org.gpodder.sailfish-zh_CN.ts, translations/harbour-org.gpodder.sailfish.ts
Adds a check and feedback to the user that migration will be needed/run in a future release.
@eson57 @carmenfdezb @sfbg @dashinfantry this adds a bunch of strings but I am not yet 100% sure of their final form your feedback is very welcome.
If/when this is merged the next PR from me will be 4.18 which will also slightly update the About text.
I also think that the next version in which the actual migration happens maybe should become 5.0.
=> Check migration
